server:
  port: 8085

api:
  key: changeme-123

jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key

springdoc:
  swagger-ui:
    persistAuthorization: false


spring:
  application:
    name: usuarios-api

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true