api:
  key: ${API_KEY:changeme-123}

jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key

springdoc:
  swagger-ui:
    persistAuthorization: false


spring:
  application:
    name: usuarios-api

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/usuarios_db}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
    username: ${SPRING_DATASOURCE_USERNAME:usuarios}
    password: ${SPRING_DATASOURCE_PASSWORD:usuarios123}

  jpa:
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
